findAllProducts:
   path: /product
   controller: App\Controller\ProductsController::findAllProducts

productCreate:
   path: /product/create
   controller: App\Controller\ProductsController::create

productDelete:
   path: /product/delete/{id}
   controller: App\Controller\ProductsController::delete

productUpdate:
   path: /product/update/{id}
   controller: App\Controller\ProductsController::update

productById:
   path: /product/{id}
   controller: App\Controller\ProductsController::findById